name: Build + Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Create test-template
      run: echo '<!DOCTYPE html><html lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8" /></head><body><div>{$html}</div></body></html>' > template.html
    - name: Convert Readme to HTML
      run: |
        mkdir artifacts
        dotnet run -p src/PeterPuff.MarkdownToHtml/PeterPuff.MarkdownToHtml.csproj -f net5.0 README.md template.html artifacts/README.html 1 0
    - name: Store converted file
      uses: actions/upload-artifact@v2
      with:
        name: readme-html
        path: artifacts/README.html

  deploy-prerelease-package:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get commit count
      id: get_commit_count
      uses: lucasfe/version_code_generator@v1.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Create prerelease package(s)
      run: dotnet pack --configuration Release --output artifacts/packages --version-suffix pre-${{ steps.get_commit_count.outputs.code }}-$CI_SHA_SHORT -p:CreatePrerelease=1
    - name: Deploy prerelease package(s) to GitHub Packages
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_API_KEY: ${{ github.token }}
      run: dotnet nuget push artifacts/packages/*.nupkg --source https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json --api-key ${{ env.GITHUB_API_KEY }} --skip-duplicate
