name: Deploy prerelease package to NuGet.org

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  deploy-prerelease-package:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get commit count
      id: get_commit_count
      uses: lucasfe/version_code_generator@v1.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Create prerelease package(s)
      run: dotnet pack --configuration Release --output artifacts/packages --version-suffix pre-${{ steps.get_commit_count.outputs.code }}-$CI_SHA_SHORT -p:CreatePrerelease=1
    - name: Deploy prerelease package(s) to NuGet.org
      env: 
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push artifacts/packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ env.NUGET_API_KEY }} --skip-duplicate
